-- 코드를 입력하세요
SELECT
    USER_ID,
    PRODUCT_ID
    # COUNT(CONCAT(USER_ID, ',', PRODUCT_ID)) AS COUNT
    FROM ONLINE_SALE
    GROUP BY CONCAT(USER_ID, ',', PRODUCT_ID)
    HAVING COUNT(CONCAT(USER_ID, ',', PRODUCT_ID)) >= 2
    ORDER BY USER_ID ASC, PRODUCT_ID DESC
    