-- 코드를 입력하세요
WITH table1 AS (
    SELECT 
        PRODUCT_ID,
        SUM(SALES_AMOUNT) AS SALES_AMOUNT
        FROM OFFLINE_SALE
        GROUP BY PRODUCT_ID
)
SELECT
    p.PRODUCT_CODE,
    p.PRICE * a.SALES_AMOUNT AS SALES
    FROM PRODUCT p
    INNER JOIN table1 a
    ON p.PRODUCT_ID = a.PRODUCT_ID
    ORDER BY p.PRICE * a.SALES_AMOUNT DESC, p.PRODUCT_CODE ASC