-- 코드를 입력하세요
SELECT 
    BOOK_ID,
    AUTHOR_NAME,
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
    FROM AUTHOR a
    INNER JOIN BOOK b
    ON a.AUTHOR_ID = b.AUTHOR_ID
    WHERE b.CATEGORY = '경제'
    ORDER BY PUBLISHED_DATE